# Based on https://github.com/galaxy119/EXILED/blob/master/.github/workflows/main.yml

name: Build

on:
  push:
    branches:
      - master
env:
  EXILED_REFERENCES: ${{ github.workspace }}/SCPStats/lib

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Nuget
      uses: iRebbok/setup-nuget@master
    
    - name: Restore Packages
      run: nuget restore SCPStats.sln
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Download references
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://www.exiled.host/build_deps/Dev.zip'
        file-name: 'References.zip'
      
    - uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://scpstats.com/websocket-sharp.dll?key=${{ secrets.WEBSOCKETSHARP }}'
        file-name: 'SCPStats/lib/websocket-sharp.dll'

    - name: Download 7zip
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://www.exiled.host/7za.exe'
        file-name: '7zip.exe'

    - name: Extract Refs
      run: ./7zip.exe e References.zip -oSCPStats/lib/ -r -y

    - name: Build
      run: msbuild SCPStats.sln -p:Configuration=release

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: Plugin DLL
        path: SCPStats/bin/Release/SCPStats*.dll
